// Generated by scripts/generate-extension-web-contributions.ts
// Do not edit by hand.

import type { ExtensionWebContribution } from "@anima/ui";

import audiobooks from "../../../../extensions/audiobooks/src/routes";
import bogart from "../../../../extensions/bogart/src/routes";
import chat from "../../../../extensions/chat/src/routes";
import control from "../../../../extensions/control/src/routes";
import editor from "../../../../extensions/editor/src/routes";
import memory from "../../../../extensions/memory/src/routes";
import presenter from "../../../../extensions/presenter/src/routes";
import scheduler from "../../../../extensions/scheduler/src/routes";

export const extensionWebContributions: ExtensionWebContribution[] = [
  audiobooks,
  bogart,
  chat,
  control,
  editor,
  memory,
  presenter,
  scheduler,
];
