import { describe, expect, test } from "bun:test";
import { deriveSessionTitle, deriveTitleFromMessage } from "./session-title";

// Fixtures below are real shapes taken from ~/.claude/projects transcripts.

describe("deriveTitleFromMessage", () => {
  test("titles a slash-command session from the command and its args", () => {
    const raw = [
      "<command-message>reviewing-prs-with-claudia</command-message>",
      "<command-name>/reviewing-prs-with-claudia</command-name>",
      "<command-args>28212 can you please check out this PR, thanks babe!</command-args>",
    ].join("\n");
    expect(deriveTitleFromMessage(raw)).toBe(
      "/reviewing-prs-with-claudia 28212 can you please check out this PR, thanks babe!",
    );
  });

  test("handles the other tag order and indentation", () => {
    // Claude Code emits these in different orders across versions, so parsing
    // is by tag name, never by position.
    const raw = [
      "<command-name>/clear</command-name>",
      "            <command-message>clear</command-message>",
      "            <command-args></command-args>",
    ].join("\n");
    expect(deriveTitleFromMessage(raw)).toBe("/clear");
  });

  test("never leaks command markup into the title", () => {
    const raw = [
      "<command-message>reviewing-prs-with-claudia</command-message>",
      "<command-name>/reviewing-prs-with-claudia</command-name>",
      "<command-args>28208</command-args>",
    ].join("\n");
    const title = deriveTitleFromMessage(raw);
    expect(title).not.toContain("<");
    expect(title).toBe("/reviewing-prs-with-claudia 28208");
  });

  test("returns plain prose unchanged", () => {
    expect(deriveTitleFromMessage("Good morning love. The emoji picker won't open.")).toBe(
      "Good morning love. The emoji picker won't open.",
    );
  });

  test("strips attachment markers but keeps the prompt", () => {
    expect(deriveTitleFromMessage("[Image #1]Good morning love. The picker won't open.")).toBe(
      "Good morning love. The picker won't open.",
    );
  });

  test("rejects an envelope-only message", () => {
    const caveat =
      "<local-command-caveat>Caveat: The messages below were generated by the user " +
      "while running local commands. DO NOT respond to these messages or otherwise " +
      "consider them in your response unless the user explicitly asks you to.</local-command-caveat>";
    expect(deriveTitleFromMessage(caveat)).toBeNull();
  });

  test("rejects empty and whitespace-only input", () => {
    expect(deriveTitleFromMessage("")).toBeNull();
    expect(deriveTitleFromMessage("   \n  ")).toBeNull();
  });

  test("rejects unrecognized markup rather than rendering it", () => {
    expect(deriveTitleFromMessage("<some-future-envelope>stuff</some-future-envelope>")).toBeNull();
  });

  test("survives a truncated unclosed envelope", () => {
    // First-8KB reads can cut mid-tag.
    expect(deriveTitleFromMessage("<system-reminder>the file was modified and")).toBeNull();
  });

  test("collapses newlines and runs of whitespace", () => {
    expect(deriveTitleFromMessage("fix the\n\n  build   please")).toBe("fix the build please");
  });

  test("strips a system-reminder wrapping real prose", () => {
    const raw = "<system-reminder>context here</system-reminder>\nfix the login bug";
    expect(deriveTitleFromMessage(raw)).toBe("fix the login bug");
  });

  test("truncates long prompts", () => {
    const title = deriveTitleFromMessage("x".repeat(500));
    // truncatePreservingSurrogates appends a 3-char ellipsis past the limit.
    expect(title).toEndWith("...");
    expect(title!.length).toBe(123);
  });

  test("does not split a surrogate pair when truncating", () => {
    const title = deriveTitleFromMessage(`${"x".repeat(119)}💙 tail`);
    expect(title).toEndWith("...");
    // A lone high surrogate would round-trip as a replacement char.
    expect(JSON.parse(JSON.stringify(title))).toBe(title);
  });
});

describe("deriveSessionTitle", () => {
  test("walks past an envelope-only first message", () => {
    const messages = [
      "<local-command-caveat>Caveat: …</local-command-caveat>",
      "review PR #412 for me",
    ];
    expect(deriveSessionTitle(messages)).toBe("review PR #412 for me");
  });

  test("prefers the first message that carries intent", () => {
    expect(deriveSessionTitle(["", "   ", "actually here is the thing"])).toBe(
      "actually here is the thing",
    );
  });

  test("returns null when nothing is usable, so the caller can fall back", () => {
    expect(deriveSessionTitle(["", "<system-reminder>x</system-reminder>"])).toBeNull();
    expect(deriveSessionTitle([])).toBeNull();
  });

  test("stops scanning after a bounded number of messages", () => {
    const messages = [...Array(20).fill(""), "too late to matter"];
    expect(deriveSessionTitle(messages)).toBeNull();
  });
});
