#!/usr/bin/env bun

import { Glob } from "bun";
import { dirname, join, relative } from "node:path";

const rootDir = join(import.meta.dir, "..");
const outputPath = join(
  rootDir,
  "packages",
  "gateway",
  "src",
  "web",
  "extension-web-contributions.generated.ts",
);
const outputDir = dirname(outputPath);

function toImportName(extensionId: string): string {
  const name = extensionId.replace(/[^a-zA-Z0-9_$]/g, "_");
  return /^[a-zA-Z_$]/.test(name) ? name : `ext_${name}`;
}

function toImportPath(filePath: string): string {
  const absolutePath = join(rootDir, filePath);
  const relativePath = relative(outputDir, absolutePath).replaceAll("\\", "/").replace(/\.ts$/, "");
  return relativePath.startsWith(".") ? relativePath : `./${relativePath}`;
}

const routeFiles = [...new Glob("extensions/*/src/routes.ts").scanSync(rootDir)].sort();
const entries = routeFiles.map((filePath) => {
  const [, extensionId] = filePath.split("/");
  return {
    extensionId,
    importName: toImportName(extensionId),
    importPath: toImportPath(filePath),
  };
});

const contents = `// Generated by scripts/generate-extension-web-contributions.ts
// Do not edit by hand.

import type { ExtensionWebContribution } from "@anima/ui";

${entries.map((entry) => `import ${entry.importName} from "${entry.importPath}";`).join("\n")}

export const extensionWebContributions: ExtensionWebContribution[] = [
${entries.map((entry) => `  ${entry.importName},`).join("\n")}
];
`;

await Bun.write(outputPath, contents);
console.log(`Generated ${relative(rootDir, outputPath)} (${entries.length} extensions)`);
